### ISSUE TITLE
Add Travis builds

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/recipe-cms#20]
The optional SilverStripe recipes (form building, collaboration etc) have all got Travis builds which run the test suites of the modules contained within the recipes. This helps us (A) to know that integration test suites are passing, and (B) to know that any config or project files we add work in context.

We should add Travis builds to this repository and the core recipe

Matching issue: https://github.com/silverstripe/recipe-core/issues/29

**Comment by robbieaverill** [comment]
PR at https://github.com/silverstripe/recipe-cms/pull/21

**Comment by stevie-mayhew** [comment]
Thanks @robbieaverill
