### ISSUE TITLE
Delete the 1 branch on this and recipe-core

### ISSUE THREAD

**Issue by sminnee** [silverstripe/recipe-cms#24]
Recipe 1.x is deprecated. The current tags should be retained to avoid breaking people's sites, but no new releases should be made. As such I think we should delete the `1`, `1.0`, and `1.1` branches.

We should do the same to recipe-core as well.

**Comment by sminnee** [comment]
Relate: https://github.com/silverstripe/recipe-core/issues/37

**Comment by ScopeyNZ** [comment]
We can't delete them until we drop support for those lines. They need to exist as long as we _might_ release new versions from those lines. In saying that we are coming up to that date: 31/03/2019

**Comment by chillu** [comment]
+1 on Sam's suggestion. I don't think we explicitly support deprecated 1.x release lines, although this will have to go alongside some comms on how we treat recipes, and potentially decouple more core versions. This should be done at the same time as solving https://github.com/silverstripe/cow/issues/132#issuecomment-465286279

@unclecheese @tractorcow Thoughts?

**Comment by tractorcow** [comment]
I just popped in to check on some bugs my developers had with upgrading.

The latest 4.1 line of silverstripe/recipe-cms is 4.1.2 (https://github.com/silverstripe/recipe-cms/releases/tag/4.1.2), but there is actually a newer version tagged 1.1.5 (https://github.com/silverstripe/recipe-cms/releases/tag/1.1.5)

If you want to switch to dropping the 1.1 line you might want to make sure the version users need to upgrade to is being properly maintained. :)

**Comment by sminnee** [comment]
Agreed - deleting the 1.1 branch will help avoid this confusion in the future.

**Comment by tractorcow** [comment]
Awesome thanks :D

**Comment by robbieaverill** [comment]
Can we do this now?

**Comment by dnsl48** [comment]
What exactly needs to be done? AFAIK the branches 1.0 and 1.1 have already been deleted.
