### ISSUE TITLE
Using Recipe-CMS as project base fails (install.php needs missing assets folder)

### ISSUE THREAD

**Issue by albanyacademy** [silverstripe/recipe-cms#25]
Trying to create project via composer using this repo as a base (as suggested in the readme) fails to fully install necessary files.

```
composer create-project silverstripe/recipe-cms --prefer-dist .
```

Go to localhost/websitename (in this case project folder was callled contracts)

```
( ! ) Fatal error: Uncaught UnexpectedValueException: RecursiveDirectoryIterator::__construct(C:\wamp64\www\contracts\public\assets,C:\wamp64\www\contracts\public\assets): The system cannot find the file specified. (code: 2) in C:\wamp64\www\contracts\vendor\silverstripe\framework\src\Dev\Install\InstallRequirements.php on line 288
--

1 | 0.0022 | 407152 | {main}( ) | ...\install.php:0
2 | 0.0057 | 408040 | include( 'C:\wamp64\www\contracts\vendor\silverstripe\framework\src\Dev\Install\install.php' ) | ...\install.php:15
3 | 0.0083 | 409080 | include( 'C:\wamp64\www\contracts\vendor\silverstripe\framework\src\Dev\Install\install5.php' ) | ...\install.php:25
4 | 0.2722 | 682280 | SilverStripe\Dev\Install\InstallRequirements->check( ) | ...\install5.php:69
5 | 0.2841 | 691544 | __construct ( ) | ...\InstallRequirements.php:288
```

Either the assets folder needs to be included as in the installer repo, or the readme should be updated to indicate this can't be used as a project base.

**Workaround**
just copying and pasting in the assets folder and its files from the installer repo mitigates this issue.

**Comment by maxime-rainville** [comment]
I confirmed the issue. `dev/build` normally creates that folder if it's missing. However, the installer doesn't appear to do it.

Could have a look to see if we can get the recipe to create the assets folder on `composer install`. Otherwise, we can try to get the `installer.php` to assets if it's missing.

Made a PR for it https://github.com/silverstripe/silverstripe-framework/pull/8890
