### ISSUE TITLE
Fix broken builds

### ISSUE THREAD

**Issue by brynwhyman** [silverstripe/recipe-cms#32]
The builds for this modules are currently failing for branches `4`, `4.5`, `4.4`, and probably `master`. See: https://travis-ci.org/silverstripe/recipe-cms/branches

@maxime-rainville raised a PR which should resolve this: https://github.com/silverstripe/silverstripe-errorpage/pull/47

- [x] Review and merge the PR
- [x] Investigate any still-failing builds, report as issues

**Comment by Cheddam** [comment]
`4` and `4.5` are green, `4.4` will be green once #33 is merged.
