### ISSUE TITLE
Short array syntax: [] vs array()

### ISSUE THREAD

**Issue by JorisDebonnet** [silverstripe/recipe-cms#4]
I notice that `Page.php` and `PageController.php` use the `array()` notation. However, the installer specifies that at least php 5.6 is required, so the shorter `[]` notation is always available. Should we not encourage this new syntax by starting the default Page class with it? 

PSR does not really make a point about it, but it seems a de facto standard since they do use it in their examples. I do notice that the Framework and CMS packages have a mix of both, but using the new syntax in the `Page.php` and `PageController.php` classes could be a first step towards encouraging both old and new developers to use it everywhere.

Also see [this StackOverflow issue](https://stackoverflow.com/questions/26651996/php-array-vs-in-method-and-variable-declaration). I would agree with the statement "_Only use array() if you want your script to run on PHP <5.4._"

**Comment by flamerohr** [comment]
Yup, a fair enough question :)
We only convert to shorthand arrays when we come across it, it's quite a timesink to continuously update code to standards - with no practical benefits.

Of course if there was a pull request, we're more than happy to review and merge :)

**Comment by JorisDebonnet** [comment]
Understood, see #5 :)
