### ISSUE TITLE
History Records are not showing the page version state correctly

### ISSUE THREAD

**Issue by hirenatfos** [silverstripe/recipe-cms#69]
[BUG: History Records are not showing the page version state correctly #255](https://github.com/silverstripe/silverstripe-versioned-admin/issues/255)

**The Records in History tab of a page are not showing the page version state correctly.**

- It shows 'Published' when the page is actually only saved but not published
- All version records turn to 'Saved' except for the first 'Created' record when the page is 'unpublished'

**Comment by GuySartorelli** [comment]
Is this the exact same issue as the one you linked to?
If so, please don't create a new issue when one already exists. Please close this issue if that's the case.

If this is actually _different_ in some way to the issue you have linked to, please explain in detail what the exact problem is and how this issue differs from the one you linked to.

**Comment by GuySartorelli** [comment]
Closing, assuming it is the same issue as the one linked to.
