### ISSUE TITLE
Multiple Deprecation errors after recipe-cms update 4.11 to 4.12

### ISSUE THREAD

**Issue by hirenatfos** [silverstripe/recipe-cms#72]
Hi Team,

We have just updated recipe-cms 4.11 to 4.12 after that when we build project we star getting errors on CLI as well on WEB Page.

Errors:

PHP Deprecated:  SilverStripe\Core\BaseKernel->getEnvironment is deprecated. Use Director::get_environm
ent_type() instead. Called from SilverStripe\Control\Director::get_environment_type. in /var/www/vendor
/silverstripe/framework/src/Dev/Deprecation.php on line 253

PHP Deprecated:  SilverStripe\Core\BaseKernel->sessionEnvironment is deprecated. Use Director::get_sess
ion_environment_type() instead. Called from SilverStripe\Core\BaseKernel->getEnvironment. in /var/www/v
endor/silverstripe/framework/src/Dev/Deprecation.php on line 253

PHP Deprecated:  SilverStripe\Core\BaseKernel->getEnvironment is deprecated. Use Director::get_environm
ent_type() instead. Called from SilverStripe\Control\HTTPApplication->getEnvironmentType. in /var/www/v
endor/silverstripe/framework/src/Dev/Deprecation.php on line 253

PHP Deprecated:  SilverStripe\Core\BaseKernel->sessionEnvironment is deprecated. Use Director::get_sess
ion_environment_type() instead. Called from SilverStripe\Core\BaseKernel->getEnvironment. in /var/www/v
endor/silverstripe/framework/src/Dev/Deprecation.php on line 253

PHP Deprecated:  SilverStripe\Core\BaseKernel->getEnvironment is deprecated. Use Director::get_environm
ent_type() instead. Called from SilverStripe\Core\BaseKernel->bootPHP. in /var/www/vendor/silverstripe/
framework/src/Dev/Deprecation.php on line 253

PHP Deprecated:  SilverStripe\Core\BaseKernel->sessionEnvironment is deprecated. Use Director::get_sess
ion_environment_type() instead. Called from SilverStripe\Core\BaseKernel->getEnvironment. in /var/www/v
endor/silverstripe/framework/src/Dev/Deprecation.php on line 253

ERROR [User Deprecated]: SilverStripe\Versioned\Versioned->allVersions is deprecated. Use Versions() in
stead. Called from SilverStripe\Versioned\Versioned->Versions.
IN GET dev/build
Line 253 in /var/www/vendor/silverstripe/framework/src/Dev/Deprecation.php

ERROR [User Deprecated]: SilverStripe\Control\HTTP::augmentState is deprecated. Use HTTPCacheControlMid
dleware instead. Called from SilverStripe\Control\Middleware\HTTPCacheControlMiddleware->process.
IN GET dev/build
Line 253 in /var/www/vendor/silverstripe/framework/src/Dev/Deprecation.php

ERROR [User Deprecated]: Config SilverStripe\Control\HTTP.cache_ajax_requests is deprecated. 'HTTP.cach
e_ajax_requests config is deprecated.
IN GET dev/build
Line 221 in /var/www/vendor/silverstripe/framework/src/Dev/Deprecation.php

Help us here please.

**Comment by GuySartorelli** [comment]
For now, I recommend turning off deprecation warnings if you're not actively looking to see if you're using deprecated code. Deprecation warnings from core code are handled better in CMS 4.13 which should be released in the next couple of weeks. We're not going to make any further changes to how deprecation warnings are handled in CMS 4.12
