### ISSUE TITLE
Get sent back to model root tab after editing any field in a tab

### ISSUE THREAD

**Issue by PixNyb** [silverstripe/recipe-cms#73]
Example: After editing a related model from a Root.Objects.OneType the user is sent back to Root (or Root.Objects if lucky)

**Comment by GuySartorelli** [comment]
Please provide a lot more details about both what you did to encounter this scenario (i.e. reproduction steps and code samples) and what behaviour you're experiencing in terms of what the user actually sees. It's not clear how to reproduce this problem, nor what exactly the problem is.

**Comment by GuySartorelli** [comment]
This issue has had no response after three weeks, and there's not enough information to even reproduce let alone fix this problem.

I'm going to close the issue. Feel free to reopen it if you can add more information.
