### ISSUE TITLE
Additional CMS Pattern Library improvements.

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/recipe-cms#75]
## Description
The following improvements need to be made:
- [x] Replace 4 space indent with a 2 space. ESlint doesn't help.
- [ ] Introduce a new library [`@storybook/addon-docs`](https://storybook.js.org/addons/@storybook/addon-docs/) to present documentation to the components.
- [x] Fix / investigate the reasons for some small warnings that happens time to time in browser console when storybook is running.

## AC's
- [x] Component stories have 2 space indent everywhere in the code.
- [ ]  `@storybook/addon-docs` is implemented and all stories that have pre-existing readme doc are using it.
- [x]  If possible there are not any warnings in the console when storybook is running.

## PR's
- https://github.com/silverstripe/silverstripe-admin/pull/1520
- https://github.com/silverstripe/silverstripe-asset-admin/pull/1365
- https://github.com/silverstripe/silverstripe-session-manager/pull/146
- https://github.com/silverstripe/silverstripe-tagfield/pull/245

**Comment by emteknetnz** [comment]
@sabina-talipova I've approved all the PRs - you can self-merge them once https://github.com/silverstripe/silverstripe-versioned-admin/pull/296 has been merged - we'd want to merge that one first so that builds go green after merging
